language: python
services:
 - docker
install:
 - make deps
script:
 - make lint || true
 - make test
 - make docker_build
 - make docker_push
deploy:
  provider: heroku
  app: agile-plains-76182
  api_key: ${HEROKU_API_KEY}
